[project]
name = "alphafold2-automation"
version = "0.1.0"
description = "Easy to run alphafold2 benchmark"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.3.5",
]

[project.optional-dependencies]
dev = ["pytest"]

[tool.pytest.ini_options]
pythonpath = [
    "."
]
