[project]
name = "alphafold2-automation"
version = "0.1.0"
description = "Easy to run alphafold2 benchmark"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.3.5",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "ruff",
    "mypy",
]

[project.scripts]
alphafold-runner = "scripts.main:main"

[tool.pytest.ini_options]
addopts = "-ra --tb=short"
testpaths = ["tests"]
pythonpath = [
    "."
]

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.mypy]
python_version = "3.12"
strict = true
files = ["scripts"]

[tool.setuptools.packages.find]
where = ["."]
include = ["scripts*"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
